### ISSUE TITLE
Driver refuses to load

### ISSUE THREAD

**Issue by seeker25** [Timboy67678/ReClass.NET-KernelPlugin#2]
I've compiled both projects and signed the driver: 

"C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe" sign /v /f D:\Experimental\ReClass.NET-KernelPlugin\bin\MySPC.pfx /t http://timestamp.verisign.com/scripts/timstamp.dll /p my_passowrd

I've also built a loader to load the library (running as admin):

```
#undef UNICODE
#include <windows.h>
#include <iostream>
int main()
{
	HINSTANCE hGetProcIDDLL = LoadLibrary("D:\\Experimental\\ReClass.NET-KernelPlugin\\bin\\x64\\KernelCore.dll");

	if (hGetProcIDDLL == NULL) {
		std::cout << "cannot locate the .dll file" << std::endl;
	}
	else {
		std::cout << "it has been called" << std::endl;
		return -1;
	}
}

```

It seems to fail on this line:

Driver.cpp:55
`if (!NT_SUCCESS(status = NtLoadDriver(&m_registry_entry))) {
`
instead of going to return false.. the function immediately exits. With status = -1073740760

My issue here is how to debug drivers I think. Any tips on how to debug or fix this issue? 

Thanks

**Comment by seeker25** [comment]
Stupid question... copy into system32 and use from there.. fixed. DependencyWalker reading the file from where it was built would show that.

**Comment by seeker25** [comment]
I have a feeling this has to do with using the windows 10 sdk.. I'll try 8.1.

**Comment by Timboy67678** [comment]
that error code is STATUS_INVALID_IMAGE_HASH, is the driver malformed? also make sure the dll and the driver are in the same directory.
Also, the dll tries to load the driver based on the current directory, which is based on the reclass.net app, as seen here

`std::wstring driver_path = fs::current_path().wstring() + L"\\Plugins\\ReClassKernel64.sys";`

**Comment by seeker25** [comment]
Yup, I made sure the path was correct, set a breakpoint checked the path exactly. I rebuilt Reclass.net, ended up getting that going but it just fails to load the plugin. 

I think my issue is I migrated to Visual Studio 2019, I'm going to try 2015. I'm trying this because I seem to get a failure on other driver loading projects trying to load it in. Maybe something to do with the SDK / DDK / VS 2019. 

This for example has changed in the project:

![image](https://user-images.githubusercontent.com/3484109/59897383-451c2180-93a1-11e9-8b96-806dac4f0308.png)

I appreciate the help Timboy, this plugin I'm hoping will help me immensely with learning Reclass.net (on handles that block traditional memory reading calls). 


Seemed to get it again on here:

![image](https://user-images.githubusercontent.com/3484109/59898546-25d3c300-93a6-11e9-9af7-973c5dff29e9.png)

STATUS_INVALID_IMAGE_NOT_MZ 

Ah I see that was because I was on debug mode. 

I put it back to release:

0xC0000428

STATUS_INVALID_IMAGE_HASH

**Comment by seeker25** [comment]
Followed this:
https://github.com/DarthTon/Blackbone/issues/218#event-1385719174

- Add cert as Trusted Root CA
- bcdedit.exe /set testsigning on
- reboot

Seems to load the driver now, trying with Reclass.net

Awesome it works! Thanks alot.

Now I need to see if I can get it to work without that flag.

**Comment by Timboy67678** [comment]
this sounds like your code signing certificate is not working properly, if it works for test signing but not for ur cert, its because you didnt buy an actual code signing certificate, and are using a self-made or test (WDKTestCert) one

**Comment by seeker25** [comment]
That sounds about right. I ended up using another project and using it to load in my driver (I think intel driver it used?). It seemed to work no problem, would need a bit of rework to make it work with Reclass.net Plugins. 

But I decided to go in another direction and work from Linux with KVM (where there is no Reclass unfortunately, unless I load it into the windows system).

**Comment by KN4CK3R** [comment]
You can run ReClass.NET in Linux. Just use Mono to run it.

https://www.youtube.com/watch?v=GkB0dCcAQVw&list=PLO246BmtoITanq3ygMCL8_w0eov4D8hjk&index=6&t=0s

**Comment by seeker25** [comment]
You're absolutely right, someone let me know about this earlier today and i'm working on it tomorrow (later on today). Appreciate it, thank you!

**Comment by seeker25** [comment]
Just a follow up: I ended up having some success loading drivers without test signing on with EfiGuard - https://github.com/Mattiwatti/EfiGuard. You can turn off driver signing verification, load the driver, turn driver signing verification back on. Closing this now.
